from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from .detection.schemas import Detection
from .detection.detector import YOLODetector

from .tracking.tracker import ByteTrackTracker
from .tracking.track_state import TrackState
from .tracking.track_manager import TrackManager

from .events.event_engine import EventEngine
from .events.schemas import Event

from .motion.motion_analyzer import (
    MotionAnalyzer,
    MotionAnalysis,
)

from .incidents.incident_engine import IncidentEngine
from .incidents.schemas import IncidentCandidate
from .incidents.evidence import IncidentEvidence


@dataclass
class VisionResult:
    """
    Result generated by the complete vision pipeline.
    """

    frame_id: int

    timestamp: datetime

    detections: list[Detection]

    tracks: list[TrackState]

    motion: list[MotionAnalysis]

    events: list[Event]

    incidents: list[IncidentCandidate]


class VisionEngine:
    """
    Main orchestration engine for the vision service.

    Pipeline:

        Frame
          ↓
        YOLO + ByteTrack
          ↓
        TrackManager
          ↓
        MotionAnalyzer
          ↓
        EventEngine
          ↓
        IncidentEngine
          ↓
        IncidentEvidence
          ↓
        VisionResult

    IMPORTANT:

    YOLO inference is executed only once per frame.

    The ByteTrackTracker internally uses:

        model.track()

    Therefore we DO NOT call:

        detector.predict()

    separately here.

    This avoids running YOLO twice on every frame.
    """

    def __init__(
        self,
        detector: YOLODetector,
        tracker: ByteTrackTracker,
        track_manager: TrackManager,
        event_engine: EventEngine,
        motion_analyzer: MotionAnalyzer,
        incident_engine: IncidentEngine,
        evidence: Optional[IncidentEvidence] = None,
    ):

        self.detector = detector

        self.tracker = tracker

        self.track_manager = track_manager

        self.event_engine = event_engine

        self.motion_analyzer = motion_analyzer

        self.incident_engine = incident_engine

        self.evidence = evidence

    # ==========================================
    # PROCESS FRAME
    # ==========================================

    def process_frame(
        self,
        frame,
        frame_id: int,
        timestamp: Optional[datetime] = None,
        persist_tracks: bool = True,
    ) -> VisionResult:
        """
        Process one complete frame through the
        vision pipeline.

        YOLO + ByteTrack are executed only once.

        persist_tracks=False on the first frame of a
        run resets the ByteTrack state carried by the
        shared YOLO model object.
        """

        if timestamp is None:
            timestamp = datetime.now()

        # ======================================
        # 1. YOLO + BYTE TRACK
        # ======================================

        """
        IMPORTANT:

        tracker.update(frame) executes:

            YOLO inference
                +
            ByteTrack

        on the COMPLETE IMAGE.

        We do NOT call:

            self.detector.predict(frame)

        because that would perform a second
        YOLO inference on the same frame.
        """

        tracked_detections = self.tracker.update(
            frame,
            persist=persist_tracks,
        )

        # ======================================
        # 2. DETECTIONS
        # ======================================

        """
        The tracker already gives us the YOLO
        detections together with their track IDs.

        Therefore we reuse them instead of running
        the detector again.
        """

        detections = tracked_detections

        # ======================================
        # 3. TRACK STATE
        # ======================================

        tracks = self.track_manager.update(
            tracked_detections
        )

        # ======================================
        # 4. MOTION ANALYSIS
        # ======================================

        motion_results = (
            self.motion_analyzer.analyze_all(
                tracks
            )
        )

        # ======================================
        # 5. EVENT ENGINE
        # ======================================

        events = self.event_engine.process(
            tracks
        )

        # ======================================
        # 6. INCIDENT ENGINE
        # ======================================

        incidents = (
            self.incident_engine.process(
                tracks=tracks,
                motion_analysis=motion_results,
            )
        )

        # ======================================
        # 7. INCIDENT EVIDENCE
        # ======================================

        if (
            self.evidence is not None
            and incidents
        ):

            for incident in incidents:

                evidence_path = (
                    self.evidence.save(
                        frame=frame,
                        incident=incident,
                        tracks=tracks,
                        frame_id=frame_id,
                    )
                )

                incident.data[
                    "evidence_path"
                ] = str(evidence_path)

        # ======================================
        # 8. RESULT
        # ======================================

        return VisionResult(
            frame_id=frame_id,

            timestamp=timestamp,

            detections=detections,

            tracks=tracks,

            motion=motion_results,

            events=events,

            incidents=incidents,
        )

    # ==========================================
    # RESET
    # ==========================================

    def reset(self):
        """
        Reset the complete vision pipeline.
        """

        self.track_manager.clear()

        self.event_engine.reset()

        self.motion_analyzer.reset()

        self.incident_engine.reset()

