from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class Event:
    """
    Represents an event generated by the
    vision event engine.
    """

    event_type: str

    timestamp: datetime

    confidence: float = 1.0

    track_ids: list[int] = field(
        default_factory=list
    )

    data: dict[str, Any] = field(
        default_factory=dict
    )