"""evidencia de incidentes

Revision ID: 18d76af8c987
Revises: 98bca952dd53
Create Date: 2026-09-08 15:48:52.305466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d76af8c987'
down_revision: Union[str, Sequence[str], None] = '98bca952dd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('evidence_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'evidence_path')
    # ### end Alembic commands ###
