"""revision humana de incidentes

Revision ID: 20bbec979fd1
Revises: 18d76af8c987
Create Date: 2026-09-08 16:00:17.946753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bbec979fd1'
down_revision: Union[str, Sequence[str], None] = '18d76af8c987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('review_status', sa.String(length=16), server_default='pendiente', nullable=False))
    op.add_column('incidents', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('reviewed_by', sa.String(length=120), nullable=True))
    op.add_column('incidents', sa.Column('review_note', sa.Text(), nullable=True))
    op.create_index('ix_incidents_review', 'incidents', ['review_status', sa.literal_column('detected_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_review', table_name='incidents')
    op.drop_column('incidents', 'review_note')
    op.drop_column('incidents', 'reviewed_by')
    op.drop_column('incidents', 'reviewed_at')
    op.drop_column('incidents', 'review_status')
    # ### end Alembic commands ###
