"""resumen de incidentes con IA

Revision ID: 610e9dfc2b32
Revises: 20bbec979fd1
Create Date: 2026-09-08 18:13:07.243069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610e9dfc2b32'
down_revision: Union[str, Sequence[str], None] = '20bbec979fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('ai_summary_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('ai_model', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'ai_model')
    op.drop_column('incidents', 'ai_summary_at')
    op.drop_column('incidents', 'ai_summary')
    # ### end Alembic commands ###
