"""cedula y telefono de usuario

Revision ID: 66ba7c160af8
Revises: d48c1a3b7f52
Create Date: 2026-09-08 23:45:28.085352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ba7c160af8'
down_revision: Union[str, Sequence[str], None] = 'd48c1a3b7f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Agrega cedula y telefono a los usuarios ya existentes.

    En tres pasos y no en uno: `cedula` es NOT NULL y UNICA, y la tabla ya
    tiene filas. Agregarla directamente fallaria —no hay valor por defecto
    que sirva, porque un default constante violaria la unicidad— asi que se
    crea anulable, se rellena con un marcador distinto por usuario y recien
    entonces se exige.

    El relleno es deliberadamente falso y reconocible: las cuentas creadas
    antes de este cambio quedan con una cedula de la forma 000000000N y hay
    que corregirlas desde el panel de administracion. Poner algo que
    pareciera real seria peor.
    """

    op.add_column("users", sa.Column("cedula", sa.String(length=20), nullable=True))
    op.add_column(
        "users",
        sa.Column("phone", sa.String(length=20), nullable=False, server_default=""),
    )

    op.execute(
        """
        UPDATE users
           SET cedula = LPAD(id::text, 10, '0')
         WHERE cedula IS NULL
        """
    )

    op.alter_column("users", "cedula", nullable=False)
    op.create_unique_constraint("uq_users_cedula", "users", ["cedula"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint("uq_users_cedula", "users", type_="unique")
    op.drop_column("users", "phone")
    op.drop_column("users", "cedula")
    op.create_table('incidents_backup_dedupe',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('cluster_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('incident_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('video_t', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frame_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('track_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('evidence_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('review_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_summary_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ai_model', sa.VARCHAR(length=64), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
