"""cameras e incidents

Revision ID: 98bca952dd53
Revises: 
Create Date: 2026-09-03 15:37:48.394018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98bca952dd53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('roi', sa.Text(), nullable=False),
    sa.Column('perspective', sa.Float(), nullable=False),
    sa.Column('occupancy_medium', sa.Float(), nullable=False),
    sa.Column('occupancy_high', sa.Float(), nullable=False),
    sa.Column('free_speed', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('cluster_id', sa.String(length=128), nullable=True),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('video_t', sa.Float(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('track_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_camera_detected', 'incidents', ['camera_id', sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('ix_incidents_type', 'incidents', ['incident_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_type', table_name='incidents')
    op.drop_index('ix_incidents_camera_detected', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('cameras')
    # ### end Alembic commands ###
