"""usuarios roles y permisos

Revision ID: ba242350f7da
Revises: f9337be8c96a
Create Date: 2026-09-08 22:04:37.542526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba242350f7da'
down_revision: Union[str, Sequence[str], None] = 'f9337be8c96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_name', 'permission_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

    _seed_roles_and_permissions()


# ----------------------------------------------------------------------
# Datos iniciales
# ----------------------------------------------------------------------
# Los roles y permisos van EN la migración y no en un script aparte porque
# sin ellos el esquema no sirve para nada: no se puede crear un usuario sin
# un rol al que asignarlo. Un despliegue nuevo queda listo con
# `alembic upgrade head`, sin un segundo paso que alguien pueda olvidar.

PERMISSIONS = {
    "stream:view": "Ver el video en vivo y la inferencia",
    "incidents:read": "Consultar el histórico de incidentes y su evidencia",
    "incidents:review": "Confirmar, descartar o archivar incidentes",
    "incidents:summarize": "Generar el resumen con IA (tiene costo por uso)",
    "cameras:read": "Ver el registro de cámaras",
    "cameras:write": "Editar cámaras y su calibración",
    "users:manage": "Crear y administrar usuarios",
}

ROLES = {
    "admin": (
        "Administra el sistema completo",
        list(PERMISSIONS),
    ),
    "operario": (
        "Vigila la operación en vivo, sin decidir sobre los incidentes",
        ["stream:view", "incidents:read", "cameras:read"],
    ),
    "analista": (
        "Revisa y clasifica los incidentes detectados",
        [
            "stream:view",
            "incidents:read",
            "incidents:review",
            "incidents:summarize",
            "cameras:read",
        ],
    ),
}


def _seed_roles_and_permissions() -> None:
    conexion = op.get_bind()

    for code, description in PERMISSIONS.items():
        conexion.execute(
            sa.text(
                "INSERT INTO permissions (code, description) VALUES (:c, :d)"
            ),
            {"c": code, "d": description},
        )

    for name, (description, codes) in ROLES.items():
        conexion.execute(
            sa.text("INSERT INTO roles (name, description) VALUES (:n, :d)"),
            {"n": name, "d": description},
        )

        for code in codes:
            conexion.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_name, permission_code) "
                    "VALUES (:r, :p)"
                ),
                {"r": name, "p": code},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
