"""homografia por camara

Revision ID: f9337be8c96a
Revises: cfb468600785
Create Date: 2026-09-08 19:02:17.528140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9337be8c96a'
down_revision: Union[str, Sequence[str], None] = 'cfb468600785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('homography', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'homography')
    # ### end Alembic commands ###
